# Generated by Django 2.2.2 on 2019-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinas', models.FloatField(verbose_name='Proteinas (gr)')),
                ('grasas', models.FloatField(verbose_name='Grasas (gr)')),
                ('carbohidratos', models.FloatField(verbose_name='Carbohidratos (gr)')),
                ('kilocalorias', models.FloatField(verbose_name='Kilocalorias (kcal)')),
                ('porcion_comestible', models.FloatField(verbose_name='Porción comestible (gr)')),
            ],
        ),
    ]
