# Generated by Django 2.2.2 on 2019-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentos',
            options={'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AddField(
            model_name='alimentos',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
